### ISSUE TITLE
qfn packages

### ISSUE THREAD

**Issue by dufguix** [LibrePCB-Libraries/LibrePCB_ICs.lplib#39]
Hi

I found all QFP packages created by python script.

Do you plan to create QFN packages in the same way ?

Have a good day

**Comment by ubruhin** [comment]
Yes that's the goal. There's a PR open but unfortunately not ready yet (also from our side not having time for review yet): https://github.com/LibrePCB/librepcb-parts-generator/pull/99

**Comment by dufguix** [comment]
Great.

This is just to complete my [ATmega lib](https://github.com/dufguix/ATmega.lplib).
I can wait.
